# Generated by Django 4.2.6 on 2023-12-01 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
                name='PackageEntry',
                fields=[
                    (
                    'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=60, verbose_name="Package's Name.")),
                    ('version', models.CharField(max_length=25, verbose_name="Package's Version.")),
                    ('os', models.CharField(choices=[('l', 'Linux'), ('w', 'Windows'), ('a', 'any')], max_length=1,
                                            verbose_name="Package's Operating System.")),
                    ('arch', models.CharField(choices=[('x', 'x86_64'), ('a', 'aarch64'), ('y', 'any')], max_length=1,
                                              verbose_name="Package's CPU Architecture.")),
                    ('kind', models.CharField(choices=[('r', 'shared'), ('t', 'static'), ('h', 'header'), ('a', 'any')],
                                              max_length=1, verbose_name="Package's kind.")),
                    ('compiler',
                     models.CharField(choices=[('g', 'gnu-like'), ('m', 'msvc-like'), ('a', 'any')], max_length=1,
                                      verbose_name="Package's compiler type.")),
                    ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Upload')),
                    ('package', models.FileField(upload_to='packages', verbose_name='Package file')),
                ],
                options={
                    'verbose_name': 'C++ Package repository item',
                },
        ),
    ]
