"""
Django settings for scripts project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
SITE_DIR = BASE_DIR.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if "SECRET_KEY" in os.environ:
    SECRET_KEY = os.environ["SECRET_KEY"]
else:
    SECRET_KEY = "django-insecure-=mnlaqamlk--(f7q19^w(6q0cfx6q&t@_^78r=9cyqwn9ux(t*"

# SECURITY WARNING: don't run with debug turned on in production!
if "DEBUG" in os.environ:
    DEBUG = os.environ["DEBUG"].lower() == "true"
else:
    DEBUG = True

DATA_DIR = Path("/app/data")
if not DATA_DIR.exists():
    DATA_DIR = SITE_DIR.parent / "data"
    DATA_DIR.mkdir(parents=True, exist_ok=True)

SITE_VERSION = "666.666.666"
SITE_HASH = "unstable"
SITE_API_VERSION = "0.0.0"

if (SITE_DIR / "VERSION").exists():
    with open(SITE_DIR / "VERSION") as fp:
        lines = fp.readlines()
    for line in lines:
        key, value = line.split(":")
        if key.strip().lower() == "version":
            SITE_VERSION = value.strip()
        elif key.strip().lower() == "api_version":
            SITE_API_VERSION = value.strip()
        elif key.strip().lower() == "hash":
            SITE_HASH = value.strip()
else:
    if "GIT_HASH" in os.environ:
        SITE_HASH = os.environ["GIT_HASH"]
#
ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
    "http://127.0.0.1:8123",
    "http://localhost:8123",
]
if "DOMAIN_NAME" in os.environ:
    CSRF_TRUSTED_ORIGINS += [
        f"http://*.{os.environ['DOMAIN_NAME']}",
        f"https://*.{os.environ['DOMAIN_NAME']}",
    ]


class LowercaseLevelNameFormatter(logging.Formatter):
    """
    Custom formatter that displays log level names in lowercase.
    """

    def format(self, record):
        record.levelname = record.levelname.lower()
        return super().format(record)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "()": "scripts.settings.LowercaseLevelNameFormatter",
            "format": "{asctime} [{levelname}] {message}",
            "datefmt": "%Y/%m/%d %H:%M:%S",
            "style": "{",
        },
        "simple": {
            "format": "{asctime} [{levelname}] {message}",
            "datefmt": "%Y/%m/%d %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "level": "DEBUG",
            "stream": "ext://sys.stdout",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": DATA_DIR / "log" / "pack.log",
            "formatter": "verbose",
            "encoding": "utf-8",
            "level": "DEBUG",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
        "propagate": False,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "pack": {
            "handlers": ["console", "file"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pack.apps.PackConfig",
    "connector.apps.ConnectorConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "scripts.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [SITE_DIR / "data" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "scripts.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / "packages.db",
    }
}
DATABASES_LOCK_PATH = DATA_DIR / "packages.lock"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = os.environ.get("LANG_CODE", "en-us")

LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]
LOCALE_PATHS = [
    SITE_DIR / "locale",
]

TIME_ZONE = os.environ.get("TZ")

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Les static
STATIC_URL = "/static/"
STATIC_ROOT = SITE_DIR / "data" / "static"

# Les medias
MEDIA_URL = "/media/"
MEDIA_ROOT = DATA_DIR

# Login redirection
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Markdownx configuration
# https://neutronx.github.io/django-markdownx/
MARKDOWNX_MARKDOWN_EXTENSIONS = [
    "markdown.extensions.extra",
    "markdown.extensions.codehilite",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
